version: "3.8"
services:
  postgres:
    image: "postgres:15.5-alpine"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${PGDATABASE}
  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "5000:80"
  api:
    image: "muhammadrio/forumapi:latest"
    environment:
      - NODE_ENV=production
      - PGUSER=${PGUSER}
      - PGHOST=postgres
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
      - ACCESS_TOKEN_KEY=${ACCESS_TOKEN_KEY}
      - REFRESH_TOKEN_KEY=${REFRESH_TOKEN_KEY}
      - ACCCESS_TOKEN_AGE=${ACCCESS_TOKEN_AGE}
    depends_on:
      - postgres